In [34]:
import os

import pandas as pd

In [35]:
plot_info = []

data_dir = "../utils"

for root, sub_dir, files in os.walk(data_dir):
    for file in files:
        if file.endswith(".csv"):
            try:
                src_file = os.path.join(data_dir, file)
                dim = int(file[3])
                obj = int(file[9])
                tree = file[16:].strip(".csv")
                df = pd.read_csv(src_file, index_col=0).fillna(0)
                df["dimension"] = dim
                df["n_objectives"] = obj
                df["tree"] = tree
                plot_info.append(df)
            except Exception as e:
                pass

In [36]:
new_df = pd.concat(plot_info)

In [37]:
new_df

,solver,exp_index,root,node_1,node_2,node_3,node_4,dimension,n_objectives,tree
0,MOEAD,67870,97,0,1,2,0,2,5,breadth
1,MOEAD,67871,98,0,1,0,1,2,5,breadth
2,MOEAD,67872,93,1,2,2,2,2,5,breadth
3,MOEAD,67873,98,0,1,1,0,2,5,breadth
4,MOEAD,67874,95,0,1,1,3,2,5,breadth
...,...,...,...,...,...,...,...,...,...,...
3302,IBEA,89783,22,78,0,0,0,5,2,breadth
3303,IBEA,89784,14,0,0,0,86,5,2,breadth
3304,IBEA,89785,15,0,0,85,0,5,2,breadth
3305,IBEA,89786,15,85,0,0,0,5,2,breadth
3306,IBEA,89787,7,0,0,0,93,5,2,breadth

In [38]:
solver = "MOEAD"
dim_n_obj_combs = [
    (2, 3),
    (2, 4),
    (2, 5),
    (3, 3),
    (3, 4),
    (3, 5),
    (4, 3),
    (4, 4),
    (4, 5),
    (5, 3),
    (5, 4),
    (5, 5),
]
tree = "breadth"
active_comb = dim_n_obj_combs[-1]

dimension = active_comb[0]
n_objectives = active_comb[1]
filtered_df = new_df[
    (new_df["solver"] == solver)
    & (new_df["dimension"] == dimension)
    & (new_df["tree"] == tree)
    & (new_df["n_objectives"] == n_objectives)
]

In [39]:
filtered_df

,solver,exp_index,root,node_1,node_2,node_3,node_4,dimension,n_objectives,tree
0,MOEAD,66066,100,0,0,0,0,5,5,breadth
1,MOEAD,66067,100,0,0,0,0,5,5,breadth
2,MOEAD,66068,100,0,0,0,0,5,5,breadth
3,MOEAD,66069,100,0,0,0,0,5,5,breadth
4,MOEAD,66070,100,0,0,0,0,5,5,breadth
...,...,...,...,...,...,...,...,...,...,...
296,MOEAD,66362,100,0,0,0,0,5,5,breadth
297,MOEAD,66363,100,0,0,0,0,5,5,breadth
298,MOEAD,66364,100,0,0,0,0,5,5,breadth
299,MOEAD,66365,100,0,0,0,0,5,5,breadth
300,MOEAD,66366,100,0,0,0,0,5,5,breadth

In [40]:
solvers = ["MOEAD", "NSGAII", "GDE3", "IBEA"]
dimensions = [2, 3, 4, 5]
n_objectives = [2, 3, 4, 5]
tree = "breadth"
df_info = []
for dimension in dimensions:
    for n_objective in n_objectives:
        for solver in solvers:
            filtered_df = new_df[
                (new_df["solver"] == solver)
                & (new_df["dimension"] == dimension)
                & (new_df["tree"] == tree)
                & (new_df["n_objectives"] == n_objective)
            ]
            if not filtered_df.empty:
                df_info.append(
                    {
                        "solver": solver,
                        "dimX": dimension,
                        "dimZ": n_objective,
                        "root_mean": filtered_df["root"].mean(),
                        "root_std": filtered_df["root"].std(),
                        "node_1_mean": filtered_df["node_1"].mean(),
                        "node_1_std": filtered_df["node_1"].std(),
                        "node_2_mean": filtered_df["node_2"].mean(),
                        "node_2_std": filtered_df["node_2"].std(),
                        "node_3_mean": filtered_df["node_3"].mean(),
                        "node_3_std": filtered_df["node_3"].std(),
                        "node_4_mean": filtered_df["node_4"].mean(),
                        "node_4_std": filtered_df["node_4"].std(),
                    }
                )

In [41]:
stat_df = pd.DataFrame(df_info)

In [42]:
stat_df

,solver,dimX,dimZ,root_mean,root_std,node_1_mean,node_1_std,node_2_mean,node_2_std,node_3_mean,node_3_std,node_4_mean,node_4_std
0,MOEAD,2,2,6.318182,2.418409,0.000000,0.000000,1.559867,11.960547,12.759424,32.140935,79.362528,33.822125
1,NSGAII,2,2,10.118136,2.924213,1.760399,12.349865,11.439268,29.888851,19.524126,37.214377,57.158070,43.376222
2,GDE3,2,2,0.000000,0.000000,0.000000,0.000000,2.329451,15.096289,7.986689,27.131282,89.683860,30.442293
3,IBEA,2,2,10.564060,3.206188,0.592346,7.242597,6.815308,23.714429,10.272879,28.347053,71.755408,35.972328
4,MOEAD,2,3,89.910596,2.965239,0.721854,0.989372,0.764901,1.231249,2.665563,3.863631,5.937086,4.135498
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,IBEA,5,4,79.013333,7.645128,0.516667,2.757123,2.646667,7.108464,3.810000,8.103051,14.013333,12.313077
60,MOEAD,5,5,99.996678,0.057639,0.000000,0.000000,0.003322,0.057639,0.000000,0.000000,0.000000,0.000000
61,NSGAII,5,5,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
62,GDE3,5,5,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
63,IBEA,5,5,92.656667,4.062075,0.636667,2.034318,1.553333,3.410659,1.616667,3.273956,3.536667,4.928450

In [43]:
solver_df = stat_df[stat_df["solver"] == "GDE3"]

In [44]:
solver_df

,solver,dimX,dimZ,root_mean,root_std,node_1_mean,node_1_std,node_2_mean,node_2_std,node_3_mean,node_3_std,node_4_mean,node_4_std
2,GDE3,2,2,0.000000,0.000000,0.000000,0.000000,2.329451,15.096289,7.986689,27.131282,89.683860,30.442293
6,GDE3,2,3,94.916667,2.306684,1.046667,1.077819,0.930000,0.949441,1.093333,1.046393,2.013333,1.519050
10,GDE3,2,4,96.290000,1.979637,0.963333,1.073544,0.963333,1.041925,0.916667,0.999861,0.866667,0.996090
14,GDE3,2,5,96.703333,2.002170,0.836667,0.905200,0.886667,1.053973,0.736667,0.869776,0.836667,0.941423
18,GDE3,3,2,16.708819,36.809692,0.851913,8.499394,4.053245,19.599587,6.881864,25.051833,71.504160,45.066585
22,GDE3,3,3,99.766667,0.446715,0.053333,0.225073,0.050000,0.218309,0.060000,0.251550,0.070000,0.268341
26,GDE3,3,4,99.746667,0.506634,0.050000,0.233126,0.076667,0.290523,0.053333,0.239472,0.073333,0.273627
30,GDE3,3,5,99.760000,0.506546,0.053333,0.225073,0.056667,0.231591,0.073333,0.261118,0.056667,0.231591
34,GDE3,4,2,94.202995,23.175678,0.003328,0.057639,1.404326,11.513959,1.001664,9.949790,3.387687,17.963791
38,GDE3,4,3,99.990000,0.099665,0.003333,0.057735,0.006667,0.081513,0.000000,0.000000,0.000000,0.000000
42,GDE3,4,4,99.990000,0.099665,0.003333,0.057735,0.000000,0.000000,0.000000,0.000000,0.006667,0.081513
46,GDE3,4,5,99.990000,0.099665,0.000000,0.000000,0.003333,0.057735,0.000000,0.000000,0.006667,0.081513
50,GDE3,5,2,99.970050,0.170592,0.006656,0.081377,0.003328,0.057639,0.006656,0.081377,0.013311,0.114699
54,GDE3,5,3,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
58,GDE3,5,4,99.996667,0.057735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003333,0.057735
62,GDE3,5,5,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [45]:
str_write = (
    f"$\operatorname{{dim}}X=3$ & Mean & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\\\ \n"
    f"$\operatorname{{dim}}Z=4$ & Std & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\\\ \hline"
)
print(str_write)

$\operatorname{dim}X=3$ & Mean & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\
$\operatorname{dim}Z=4$ & Std & X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY &X.XX & Y.YY \\ \hline

In [46]:
def compose_latex_rows(solvers_data: list, dimension: int, n_objective: int):
    mean_string = f"$\operatorname{{dim}}X={dimension}$ & Mean "
    std_string = f"$\operatorname{{dim}}Z={n_objective}$ & Std "
    for solver_data in solvers_data:
        mean_string += f"& {solver_data['root_mean']} & {solver_data['node_1_mean']} & {solver_data['node_2_mean']} & {solver_data['node_3_mean']} & {solver_data['node_4_mean']} "
        std_string += f"& {solver_data['root_std']} & {solver_data['node_1_std']} & {solver_data['node_2_std']} & {solver_data['node_3_std']} &{solver_data['node_4_std']} "
    return mean_string + "\\\\ \n" + std_string + "\\\\ \\hline \n"

In [47]:
for dimension in dimensions:
    for n_objective in n_objectives:
        res_df = stat_df[(stat_df["dimX"] == dimension) & (stat_df["dimZ"] == n_objective)]
        res_df = res_df.round(2)
        if not res_df.empty:
            data_list = [
                res_df[res_df["solver"] == "GDE3"].iloc[0],
                res_df[res_df["solver"] == "NSGAII"].iloc[0],
                res_df[res_df["solver"] == "MOEAD"].iloc[0],
            ]
            print(compose_latex_rows(solvers_data=data_list, dimension=dimension, n_objective=n_objective))
#             s1 = (res_df[res_df['solver']=='GDE3'].iloc[0])
#             s2 = (res_df[res_df['solver']=='NSGAII'].iloc[0])
#             str_write = (f"$\operatorname{{dim}}X={dimension}$ & Mean & {s1['root_mean']} & {s1['node_1_mean']} & {s1['node_2_mean']} & {s1['node_3_mean']} &{s1['node_4_mean']} "
#                          f"& {s2['root_mean']} & {s2['node_1_mean']} & {s2['node_2_mean']} & {s2['node_3_mean']} &{s2['node_4_mean']} \\\\ \n"
#             f"$\operatorname{{dim}}Z={n_objective}$ & Std & {s1['root_std']} & {s1['node_1_std']} & {s1['node_2_std']} & {s1['node_3_std']} &{s1['node_4_std']}  "
#             f"& {s2['root_std']} & {s2['node_1_std']} & {s2['node_2_std']} & {s2['node_3_std']} &{s2['node_4_std']} \\\\ \hline")
#             print(str_write)
#             print("\n")

$\operatorname{dim}X=2$ & Mean & 0.0 & 0.0 & 2.33 & 7.99 & 89.68 & 10.12 & 1.76 & 11.44 & 19.52 & 57.16 & 6.32 & 0.0 & 1.56 & 12.76 & 79.36 \\
$\operatorname{dim}Z=2$ & Std & 0.0 & 0.0 & 15.1 & 27.13 &30.44 & 2.92 & 12.35 & 29.89 & 37.21 &43.38 & 2.42 & 0.0 & 11.96 & 32.14 &33.82 \\ \hline

$\operatorname{dim}X=2$ & Mean & 94.92 & 1.05 & 0.93 & 1.09 & 2.01 & 91.78 & 0.46 & 0.48 & 1.33 & 5.95 & 89.91 & 0.72 & 0.76 & 2.67 & 5.94 \\
$\operatorname{dim}Z=3$ & Std & 2.31 & 1.08 & 0.95 & 1.05 &1.52 & 4.64 & 0.99 & 0.96 & 2.82 &4.93 & 2.97 & 0.99 & 1.23 & 3.86 &4.14 \\ \hline

$\operatorname{dim}X=2$ & Mean & 96.29 & 0.96 & 0.96 & 0.92 & 0.87 & 95.15 & 1.38 & 1.16 & 1.13 & 1.18 & 94.77 & 0.94 & 1.0 & 1.4 & 1.89 \\
$\operatorname{dim}Z=4$ & Std & 1.98 & 1.07 & 1.04 & 1.0 &1.0 & 2.96 & 1.97 & 1.82 & 1.79 &1.96 & 2.12 & 0.99 & 1.09 & 1.49 &1.71 \\ \hline

$\operatorname{dim}X=2$ & Mean & 96.7 & 0.84 & 0.89 & 0.74 & 0.84 & 96.49 & 0.73 & 0.83 & 1.04 & 0.91 & 96.58 & 0.84 & 0.8 & 0.92 & 0.85 \\
$\operatorname{dim}Z=5$ & Std & 2.0 & 0.91 & 1.05 & 0.87 &0.94 & 2.73 & 1.36 & 1.5 & 1.73 &1.57 & 1.81 & 0.93 & 0.87 & 1.03 &0.93 \\ \hline

$\operatorname{dim}X=3$ & Mean & 16.71 & 0.85 & 4.05 & 6.88 & 71.5 & 12.71 & 3.93 & 19.5 & 26.2 & 37.65 & 8.78 & 1.73 & 14.4 & 21.09 & 53.99 \\
$\operatorname{dim}Z=2$ & Std & 36.81 & 8.5 & 19.6 & 25.05 &45.07 & 3.52 & 17.83 & 36.48 & 40.15 &43.35 & 2.82 & 12.45 & 33.35 & 38.45 &44.9 \\ \hline

$\operatorname{dim}X=3$ & Mean & 99.77 & 0.05 & 0.05 & 0.06 & 0.07 & 99.38 & 0.08 & 0.11 & 0.1 & 0.34 & 92.42 & 0.82 & 1.37 & 2.22 & 3.17 \\
$\operatorname{dim}Z=3$ & Std & 0.45 & 0.23 & 0.22 & 0.25 &0.27 & 1.78 & 0.35 & 0.48 & 0.43 &1.58 & 2.5 & 2.07 & 2.81 & 3.64 &3.93 \\ \hline

$\operatorname{dim}X=3$ & Mean & 99.75 & 0.05 & 0.08 & 0.05 & 0.07 & 99.14 & 0.26 & 0.24 & 0.14 & 0.21 & 98.06 & 0.35 & 0.39 & 0.49 & 0.71 \\
$\operatorname{dim}Z=4$ & Std & 0.51 & 0.23 & 0.29 & 0.24 &0.27 & 1.36 & 0.82 & 0.78 & 0.51 &0.64 & 1.24 & 0.75 & 0.76 & 0.91 &1.03 \\ \hline

$\operatorname{dim}X=3$ & Mean & 99.76 & 0.05 & 0.06 & 0.07 & 0.06 & 99.68 & 0.09 & 0.09 & 0.04 & 0.11 & 99.48 & 0.09 & 0.13 & 0.15 & 0.16 \\
$\operatorname{dim}Z=5$ & Std & 0.51 & 0.23 & 0.23 & 0.26 &0.23 & 0.75 & 0.42 & 0.38 & 0.19 &0.44 & 0.72 & 0.29 & 0.37 & 0.4 &0.39 \\ \hline

$\operatorname{dim}X=4$ & Mean & 94.2 & 0.0 & 1.4 & 1.0 & 3.39 & 14.84 & 6.51 & 19.0 & 24.42 & 35.23 & 10.92 & 10.71 & 18.09 & 21.17 & 39.11 \\
$\operatorname{dim}Z=2$ & Std & 23.18 & 0.06 & 11.51 & 9.95 &17.96 & 3.66 & 22.16 & 35.53 & 38.79 &42.13 & 3.06 & 28.96 & 35.81 & 38.03 &44.32 \\ \hline

$\operatorname{dim}X=4$ & Mean & 99.99 & 0.0 & 0.01 & 0.0 & 0.0 & 99.98 & 0.0 & 0.0 & 0.01 & 0.0 & 93.26 & 0.99 & 1.5 & 1.8 & 2.44 \\
$\operatorname{dim}Z=3$ & Std & 0.1 & 0.06 & 0.08 & 0.0 &0.0 & 0.13 & 0.06 & 0.0 & 0.1 &0.06 & 2.25 & 2.36 & 2.84 & 3.13 &3.63 \\ \hline

$\operatorname{dim}X=4$ & Mean & 99.99 & 0.0 & 0.0 & 0.0 & 0.01 & 99.91 & 0.01 & 0.04 & 0.02 & 0.03 & 98.83 & 0.15 & 0.15 & 0.24 & 0.29 \\
$\operatorname{dim}Z=4$ & Std & 0.1 & 0.06 & 0.0 & 0.0 &0.08 & 0.36 & 0.08 & 0.27 & 0.15 &0.18 & 5.78 & 0.52 & 0.46 & 0.57 &0.69 \\ \hline

$\operatorname{dim}X=4$ & Mean & 99.99 & 0.0 & 0.0 & 0.0 & 0.01 & 99.99 & 0.0 & 0.0 & 0.0 & 0.01 & 99.94 & 0.03 & 0.01 & 0.01 & 0.01 \\
$\operatorname{dim}Z=5$ & Std & 0.1 & 0.0 & 0.06 & 0.0 &0.08 & 0.1 & 0.0 & 0.0 & 0.06 &0.08 & 0.23 & 0.16 & 0.1 & 0.1 &0.1 \\ \hline

$\operatorname{dim}X=5$ & Mean & 99.97 & 0.01 & 0.0 & 0.01 & 0.01 & 14.75 & 9.82 & 21.66 & 22.16 & 31.62 & 11.63 & 9.98 & 20.28 & 21.52 & 36.57 \\
$\operatorname{dim}Z=2$ & Std & 0.17 & 0.08 & 0.06 & 0.08 &0.11 & 4.05 & 26.27 & 37.3 & 37.64 &41.7 & 3.1 & 27.87 & 37.25 & 37.97 &43.66 \\ \hline

$\operatorname{dim}X=5$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 & 93.83 & 0.97 & 1.26 & 1.79 & 2.16 \\
$\operatorname{dim}Z=3$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0 & 0.0 & 0.0 & 0.0 & 0.0 &0.0 & 2.21 & 2.4 & 2.55 & 2.98 &3.33 \\ \hline

$\operatorname{dim}X=5$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 & 99.67 & 0.06 & 0.07 & 0.1 & 0.11 \\
$\operatorname{dim}Z=4$ & Std & 0.06 & 0.0 & 0.0 & 0.0 &0.06 & 0.06 & 0.0 & 0.0 & 0.06 &0.0 & 0.66 & 0.29 & 0.31 & 0.39 &0.43 \\ \hline

$\operatorname{dim}X=5$ & Mean & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 & 100.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
$\operatorname{dim}Z=5$ & Std & 0.0 & 0.0 & 0.0 & 0.0 &0.0 & 0.0 & 0.0 & 0.0 & 0.0 &0.0 & 0.06 & 0.0 & 0.06 & 0.0 &0.0 \\ \hline